### ISSUE TITLE
Publish as NuGet

### ISSUE THREAD

**Issue by xperiandri** [BADF00D/DisposableFixer#104]
Have you published this extension as NuGet analyzer?

**Comment by BADF00D** [comment]
Currently not, do you need this?

**Comment by xperiandri** [comment]
Yes, it would be nice to install into projects and force other teammates to have it in Visual Studio and on CI build

**Comment by BADF00D** [comment]
Ok, should be no big problem. As I remember NuGet publish is already build-in into VS, I think I only have to upload  the package to nuget.org.

Before you force others to use this tool, be aware of the problem mentioned in #35.  I currently have no solution for this. So maybe you have some false positive detections for not disposed instances.

**Comment by xperiandri** [comment]
Thank

**Comment by BADF00D** [comment]
Hi,
I just uploaded a package to [nuget.org](https://www.nuget.org/packages/DisposableFixer/1.4.0).
But I'm not sure if the package is correct, because I can remember I read the there should be no dependencies for analyzer packages.  But give it a try, maybe my memory is wrong.

**Comment by xperiandri** [comment]
Super cool! I've tested, it works
