### ISSUE TITLE
False detections

### ISSUE THREAD

**Issue by twenzel** [BADF00D/DisposableFixer#11]
Following lines will be false positive:

- System.IO.Directory.GetDirectories("any dir")
- System.IO.Directory.GetFiles("any dir")
- nameof(any property of a type)

**Comment by BADF00D** [comment]
Thanks for submitting this issue. I was able to reproduce the error and will fix it soon.

**Comment by BADF00D** [comment]
I just uploaded the version 0.9 that contains the bugfix for your issue. It already available.
