### ISSUE TITLE
conditional in Using statement incorrectly warns

### ISSUE THREAD

**Issue by AartBluestoke** [BADF00D/DisposableFixer#115]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: 1.6.0
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
if you have a condition to decide which of 2 potential disposables (eg, 2 different ways to get a database connection) inside the using statement, then it warns that they are not disposed, even though the one returned to the using will be.

### Source Code

```csharp
        Func<IDisposable> f=()=>null;
        public void disposableTest(bool flag)
        {
            using (flag?f():f()) // whichever one we used will be disposed, but we get a warning on both
            { }
        }
```

### Screenshot
also the suggested 'fix' changes the semantic behaviour to always create that IDisposable from the call, rather than just the one we decide to use.
![image](https://user-images.githubusercontent.com/1892829/62016274-826f9c80-b1f4-11e9-9d9e-a06210378dff.png)

**Comment by BADF00D** [comment]
Hi, thanks for reporting. 
Currently each MethodeInvocation are analysed independently from each other, causing this bug. I think this should be possible to fix. The problem CodeFixes should be gone automatically, since the there will be no more "undispose anonymous variable" warnings

**Comment by BADF00D** [comment]
Will be part of release 1.7.0
