### ISSUE TITLE
Unexpected DF0001 when yield returning a disposable

### ISSUE THREAD

**Issue by AartBluestoke** [BADF00D/DisposableFixer#117]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of DisposableFixer: 1.6.0
- [X] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
yield return of a disposable warns about an undisposed object, while a simple return is flagged safe. ; i would not expect this inconsistency.

### Source Code

```csharp
    class someTest
    {
        static IDisposable f()=>null;
        IEnumerable<IDisposable> f2()
        {
            foreach(var r in Enumerable.Range(1, 10))
            {
                yield return f(); // warning here -- would expect the warning status to be the same as below.
            }
        }

        IDisposable f3()
        { 
            return f(); // no warning here
        }
    }
```

### Screenshot

![image](https://user-images.githubusercontent.com/1892829/62028166-f759cb00-b222-11e9-96cd-1f39c0802464.png)

**Comment by BADF00D** [comment]
Hi, thanks for reporting. Actually I never thought about this "feature" of yielding an IDisposable. Should be no big deal

**Comment by BADF00D** [comment]
Will be part of release 1.7.0
