### ISSUE TITLE
Using a tracking type/tracking method to dispose fields/properties initialized in constructor leads to a warning

### ISSUE THREAD

**Issue by Claye-L** [BADF00D/DisposableFixer#124]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: 2.0.0
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Initialize a IDisposable property or field in the constructor. Add it to a tracking type (CompositeDisposable here).Get a warning "Field/Property not disposed";

### Source Code
```csharp
 public class BaseCase : IDisposable
    {
        private MemoryStream field;
        public MemoryStream Property { get; set; }
        public BaseCase()
        {
            field = new MemoryStream(); //no warning as expected
            Property = new MemoryStream(); //no warning as expected
        }

        public void Dispose()
        {
            field.Dispose();
            Property.Dispose();
        }
    }

    public class WithTrackingMethod : IDisposable
    {
        private MemoryStream field;
        public MemoryStream Property { get; set; }
        private CompositeDisposable disposables;
        public WithTrackingMethod()
        {
            disposables = new CompositeDisposable(); //no warning as expected
            field = new MemoryStream(); //Warning : Field not disposed, should not be
            Property = new MemoryStream(); //Warning : Property not disposed, should not be
            var local = new MemoryStream(); //no warning as expected

            disposables.Add(local);
            disposables.Add(field);
            disposables.Add(Property);
        }
        public void Dispose()
        {
            disposables.Dispose();
        }
    }
```

**Comment by BADF00D** [comment]
@Claye-L 
I evaluated the problem last weekend and was able to fix it. I detected similar situation that causes the same problem and tries to fix them, too. Unfortunately all my testrunners went nuts, so I was not able to finish the ticket yet.

**Comment by BADF00D** [comment]
Will be part of next release
