### ISSUE TITLE
Using expression syntax for method declarations doesnt notify of undisposed object

### ISSUE THREAD

**Issue by Claye-L** [BADF00D/DisposableFixer#140]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of DisposableFixer: YOUR_VERSION
- [ ] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Instantiating a disposable using method expression syntax doesn't highlight it whereas using the full bracket syntax does.

### Source Code

```csharp
void MakeStream() => new MemoryStream();
void MakeStreamToo()
  {
     var m = new MemoryStream();
  }
```

### Screenshot

![image](https://user-images.githubusercontent.com/43422061/72511573-a9299a00-384b-11ea-9f0b-a6712f7e4425.png)

**Comment by BADF00D** [comment]
Hi,
thanks for reporting. I actually was not aware, that the first expression is valid C# code. I thought there have to be an return type. Should be easy to fix.

**Comment by BADF00D** [comment]
Will be part of release 2.4.1 for Visual Studio 2017 and 3.2.1 for Visual Studio 2019
