### ISSUE TITLE
No code fix for Using declarations

### ISSUE THREAD

**Issue by Thaoden** [BADF00D/DisposableFixer#147]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: Disposable Fixer 2019 3.2.2
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When accessing code fixes for DF0010 "Local variable is not disposed", only "Dispose after last usage", "Create field and dispose in Dispose() method", and "Wrap in using" are offered. "Use Using declaration" or something similar would be a nice addition to the list.

### Source Code

```csharp
private void MyMethod(){
    var msg = new HttpResponseMessage();
}
```

### Screenshot

![Disposable](https://user-images.githubusercontent.com/3832723/75784731-f06bdb80-5d62-11ea-8f3a-d2a50602d042.PNG)

**Comment by BADF00D** [comment]
Your are right, that would be nice. Thanks you for suggesting this feature

**Comment by BADF00D** [comment]
There are two new code fixes available:
* local variables can be disposed via using declaration
* anonymous variables can be disposed via using declaration (an new local variable gets declared automatically)

Will be part of release 3.3.0 (just released). Happy coding!
