### ISSUE TITLE
JsonTextWriter

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#32]
On Dispose of JsonTextWriter, the Close method is called which disposes the given StreamWriter.
So it should not yield a "not disposed" warning.

_writer = new JsonTextWriter(new StreamWriter(stream, encoding, buffer_size, leave_open));

**Comment by BADF00D** [comment]
Basically JsonTextWriter had to be added to list of tracking types. For this, I need the full namespace of this type, all signatures of the constructors and which of them are tracking or not.

**Comment by dscopra** [comment]
Newtonsoft.Json.JsonTextWriter
Newtonsoft.Json.Bson.BsonWriter
Newtonsoft.Json.Serialization.TraceJsonWriter
