### ISSUE TITLE
Add support for Rx

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#34]
CompositeDisposable from System.Reactive.Disposables tracks disposable instances. 
Disposable Instances given to its ctor or added via Add(dispo) should not be marked as disposed.

**Comment by dscopra** [comment]
Tracking methods calls:
Reactive.Bindings.Extensions.IDisposableExtensions.AddTo<T>(this T disposable,  ICollection<IDisposable> container) where T : Disposable

**Comment by BADF00D** [comment]
Fixed in version 0.26.0.0
