### ISSUE TITLE
Add CodeFix to dispose undisposed field variables in Dispose method

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#42]
If I stumble upon an undisposed field/property, there should be a code fix, that disposes this field/property in Dispose(). If there is no dispose method, it should be created and the IDisposable interface should be added.

**Comment by BADF00D** [comment]
When using code fix, there are some problem:

- using for ``System`` is not added
- If ObjectCreation implements IDisposable but stored property dosn't, the call to the property has to call ``(prop as IDisposable)?.Dispose()`` instead of ``prop.Dispose()``

**Comment by BADF00D** [comment]
Will be part of release 0.39
