### ISSUE TITLE
Cannot update or (re)install this in visual studio 2017 with lastest version  0.23

### ISSUE THREAD

**Issue by nuelle1605** [BADF00D/DisposableFixer#47]
VS detect new version but cannot update.
Error message points to unresolved dependencies.

**Comment by BADF00D** [comment]
I found and reproduce the problem. Fix in progress...

**Comment by BADF00D** [comment]
I just uploaded version 0.24. This fixed the problem for me. In a few minutes the update should be available via Visual Studio Gallery.
