### ISSUE TITLE
Add support for method from FakeItEasy A.Fake<IDisposable>

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#50]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If you create an instance of an Interface that implements IDisposable, it is marked as not disposed.
But if it is created via ```A.Fake<IDisposable>``` there is nothing to disposed, Because there are no resources that have to be disposed and the actual call to Dispose does nothing. So this Disposable can be ignored.

### Source Code
```csharp
public class SomeClass{
    private readonly IDisposable _fake = A.Fake<IDisposable>();
}
```

### Screenshot

![image](https://user-images.githubusercontent.com/13195823/28405300-ffa9e7dc-6d2c-11e7-9bfa-841118d1b360.png)

**Comment by BADF00D** [comment]
Will be part of release 0.28
