### ISSUE TITLE
There should be exceptions for fields and properties not disposed in Dispose-method

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#55]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
There was similar request in issue #20, that got the label wontfix.

### Description
In some situations it is impractical to enforce to dispose all fields and properties in Dispose-method. For instance in Unit Test there is often a special way for tearing down your tests. E.g. in Spec Test, the cleanup tasks are done within a method named Cleanup. In NUnit 2 Tests there is a method with an attribute called TearDownAttribute.

In fact it does not hurt, when these fields and properties get disposed in Dispose method, too, But it is extra work only to tell the extension, that everything is ok.

My proposal is, to allow dispose of fields and properties in more than the Dispose method. It also can be restricted to certain user-defined method in used-defined class. E.g.: Cleanup in classes that derive from Spec. Method with attribute called Teardown

### Screenshot
![image](https://user-images.githubusercontent.com/13195823/28907681-b05a9eb2-781f-11e7-8a68-754cf5c3876e.png)

**Comment by BADF00D** [comment]
Will be part of release 0.28
