### ISSUE TITLE
Add CompositeDisposable.Add to tracking methods

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#56]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When adding an IDisposable to an CompositeDisposable via its Add(IDisposable) method, I got an diagnostics. 

### Source Code
```csharp
var disposables = new CompositeDisposable();
disposables.Add(new MemoryStream())//should not yield an diagnostic
disposables.Dispose();
```

### Screenshot
![image](https://user-images.githubusercontent.com/13195823/29565444-3bf37dba-8746-11e7-8198-6c053775bd38.png)

Signatures: 
* System.Reactive.Disposables.CompositeDisposable.Add(IDisposable item)
* new System.Reactive.Disposables.CompositeDisposable(params IDisposable[] disposables)
* new System.Reactive.Disposables.CompositeDisposable(IEnumerable<IDisposable> disposables)

**Comment by BADF00D** [comment]
Will be part of Release 0.29
