### ISSUE TITLE
Extends support for FakeItEasy

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#57]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In issue #50 a basic support for FakeItEasy was added. Unfortunately this is not complete. The following code yields an diagnistic:

### Source Code
```chsarp
A.Fake<MockStream>(o => o.Strict());
```

### Screenshot

![image](https://user-images.githubusercontent.com/13195823/29770387-1fc78c6e-8bef-11e7-9eea-317d7ce5a2e3.png)

**Comment by BADF00D** [comment]
Added support for following calls:
```csharp
A.Fake<IDisposable>(o => o.Strict());
A.Fake<IDisposable>();
A.CollectionOfFake<IDisposable>(2);
A.CollectionOfFake<IDisposable>(2, o => o.Strict());
A.Dummy<IDisposable>();
A.CollectionOfDummy<IDisposable>(3);
```
