### ISSUE TITLE
Add LumenWorks.Framework.IO.Csv.CsvReader to whitelist

### ISSUE THREAD

**Issue by coxymla** [BADF00D/DisposableFixer#62]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: 0.29
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
CsvReader has a constructor that takes in a stream. When the CsvReader is disposed, the stream is disposed.
Currently DisposableFixer detects the anonymous stream as not being disposed. It would be great if it was added to the whitelist.

### Source Code
`using (var csv = new CsvReader(new StreamReader(outputFilename), false))
{
    // do stuff
}`

### Screenshot
![image](https://user-images.githubusercontent.com/691623/30254992-05d60702-96d2-11e7-96b8-0e09d7ad9a4f.png)

**Comment by BADF00D** [comment]
I just looked up the code in [CsvReader](https://github.com/phatcher/CsvReader/blob/master/code/LumenWorks.Framework.IO/Csv/CsvReader.cs). 
I could not find a constructor with a _leaveOpen_-flag. So every instance is is always tracking the given stream. It should be no problem at all.

Thanks reporting!

**Comment by BADF00D** [comment]
Will be part of release 0.30
