### ISSUE TITLE
Support for IWindsorContainer.Register

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#63]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of DisposableFixer: 0.30
- [X] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
This methods returns the container itsself und should not be disposed.

### Source Code
```csharp
public void Install(IWindsorContainer container, IConfigurationStore store) {
            container.Register(Registrations().ToArray());
        }
```

### Screenshot
![image](https://user-images.githubusercontent.com/13195823/30369654-88e71b0a-9875-11e7-8094-2f3935569fb5.png)

**Comment by dscopra** [comment]
Add IWindsorContainer.Register(....)

**Comment by BADF00D** [comment]
Will be part of release 0.33
