### ISSUE TITLE
Analyzer throwing NullReferenceException during build.

### ISSUE THREAD

**Issue by ericwra** [BADF00D/DisposableFixer#64]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: 0.30
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Some projects cause DisposableFixer to throw a System.NullReferenceException on Build.

Analyzer 'DisposableFixer.DisposableFixerAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

### Source Code
I have not been able to isolate this problem outside of my very large solution. If I recreate the project it is throwing on outside of the large solution it seems to have no issues during build.

### Screenshot
![](https://i.imgur.com/NslGq9S.png)

**Comment by BADF00D** [comment]
Thanks for reporting the error. 
Can you make another screenshot, where I can see the stacktrace? Simply click on the small triangle in front of each line. 
I just inserted a NotImplmentedException in another extension to demonstrate this:
![image](https://user-images.githubusercontent.com/2852160/30438496-a5edc36e-9971-11e7-8512-d1555ec46088.png)

**Comment by BADF00D** [comment]
I just saw you are running version 0.12. This is one of the first version I published. There are lots of known bugs. The current version 0.30 might already solve your problem.

You can enable autoupdate. Then new versions will automatically downloaded and installed, if you restart Visual Studio.

**Comment by ericwra** [comment]
I was mistaken about the version number. I have the latest from the visual studios marketplace / gallery version 0.30.

I've attached a screenshot with the stacktrace as requested.


![](https://i.imgur.com/3H5dh7J.png)

**Comment by BADF00D** [comment]
Hi, 
unfortunately I was not able to reproduce the problem, yet. But I refactored the code and split the method into several once. I published version 0.31 with this changes.

Can you once more try to reproduce the problem and send me a screenshot of the new stacktrace?

**Comment by ericwra** [comment]
I've updated to 0.31 and will see if I can get the error to return this afternoon.

**Comment by BADF00D** [comment]
Thanks for the new stacktrace.

**Comment by ericwra** [comment]
No problem, let me know if there is anything I can do to help you track this down. I find this extension very useful when refactoring large code bases.

**Comment by BADF00D** [comment]
I think I finally found the problem. Do you use property initializers? Something like:

```csharp
using System;
using System.IO;
namespace SomeNamespace{
    internal class Program {
        private static void Main(string[] args) {
            var memoryStream = new MemoryStream();
            new Foo {Prop = memoryStream};//this causes the problem
        }
    }

    internal class Foo {
        public IDisposable Prop { get; set; }
        public Foo() { }
    }
}
```

Can you please add the optional braces and check if the error is gone?


```csharp
using System;
using System.IO;
namespace SomeNamespace{
    internal class Program {
        private static void Main(string[] args) {
            var memoryStream = new MemoryStream();
            new Foo (){Prop = memoryStream};//should be fixed with braces
        }
    }

    internal class Foo {
        public IDisposable Prop { get; set; }
        public Foo() { }
    }
}
```

I thought that each constructor should have a (maybe empty) ArgumentList, but when using property initializer the ArgumentList is actually null, instead of empty. 

If you can verify the solution, the fix should be very easy.

**Comment by ericwra** [comment]
That fixed the issue. Thanks for tracking down this exception!

**Comment by BADF00D** [comment]
By the way, which version of Visual Studio are you using? 2015/2017, Community Edition, Professional, Enterprise?
I'm asking because currently I wasn't able to spot this problem on my own.

**Comment by BADF00D** [comment]
Is part of release 0.32
