### ISSUE TITLE
Disposing using the protected virtual pattern does not seem to be detected.

### ISSUE THREAD

**Issue by ericwra** [BADF00D/DisposableFixer#65]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: 0.31
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When using the protected virtual pattern for disposing,  fields are detected as not disposed.

### Source Code
```csharp
     public class ExampleManager : IExampleService, IDisposable
     {
     	private readonly _db;
     
     	public ExampleManager() 
        {
        	_db = new ExampleEntities(); // This is detected as not disposed.
        }
     
     	private bool disposing;

        protected virtual void Dispose(bool disposing)
        {
            if (!disposing)
            {
                if (disposing)
                {
                    _db.Dispose();
                }

                //Dispose of unmanaged resouces here

                disposing = true;
            }
        }

        ~ExampleManager() {
           Dispose(false);
        }

        public void Dispose()
        {
            Dispose(true);
        }
    }
```

**Comment by BADF00D** [comment]
Will be part of release 0.33

**Comment by ericwra** [comment]
Perfect! Thank you for addressing my issues!
