### ISSUE TITLE
Properties that use extension in getter yield undisposed property

### ISSUE THREAD

**Issue by dscopra** [BADF00D/DisposableFixer#66]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: 0.31
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using extension any methods within a property, there is an _Property not disposed_ warning, besides there is no IDisposable at all. When using an ExpressionBody instead, the warning disappears.

### Source Code
```csharp
using System;

namespace ExtensionMethodYieldsNotDisposed {
    internal class ErrorInExtensionMethods {
        public DateTimeOffset Timestamp { get; set; }

        public bool IsNewGetter
        {
            get { return Timestamp.IsNull(); }
        }

        public bool IsNewExpressionBody => Timestamp.IsNull();

        public string EmptyStringGetter
        {
            get { return Timestamp.ReturnStringEmpty(); }
        }
    }

    public static class ObjectExtensions {
        public static bool IsNull(this object @object) {
            return ReferenceEquals(@object, null);
        }

        public static string ReturnStringEmpty(this object @object) {
            return string.Empty;
        }
    }
}

```

### Screenshot
![image](https://user-images.githubusercontent.com/13195823/30630914-b8122ba0-9de2-11e7-837f-f21d5633e319.png)

**Comment by BADF00D** [comment]
The problem is, that the analysis of the MethodInvocation never checks if the return type implements IDisposable and therefore should be checked at all.

DisposableAnalyser:308 
```csharp
if (type == null) { } 
else if (node.IsParentADisposeCallIgnoringParenthesis()) 
```
 Should be:

````csharp
if (type == null) { } 
else if (!ImplementsIDisposable(type)) return;
else if (node.IsParentADisposeCallIgnoringParenthesis()) 
```
