### ISSUE TITLE
Close() corresponding Dispose()

### ISSUE THREAD

**Issue by leluc42** [BADF00D/DisposableFixer#70]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of DisposableFixer: 0.34
- [x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If i have an object, like an SerialPort, which implements an Close()-method, there is the Error DF0010 (Local variable is not disposed) to. But the Close()-method normally is calling the Dispose()-method. Definitely the original classes from the .Net Framework implement this behaviour. 

In fact, it should not be an  Error, if an object's Close()-method is called.

### Source Code
SerialPort  port= new SerialPort();
port.Close();

**Comment by BADF00D** [comment]
Hi,
first of all, thanks for reporting this error.

I just disassembled SerialPort and could confirm what you are saying. Its pretty uncommon that `Dispose` is called by another method within the same class. Usually a method like `Close` calls `Dispose`, e.g. in `Stream` and nearly everything that is derived from `Stream`:
```csharp
public void Dispose() {
	/* These are correct, but we'd have to fix PipeStream & NetworkStream very carefully.
	Contract.Ensures(CanRead == false);
	Contract.Ensures(CanWrite == false);
	Contract.Ensures(CanSeek == false);
	*/
	Close();
}
```
I'm still thinking what is the best way to handle this special situation...

**Comment by BADF00D** [comment]
Will be fixed in version 0.35

**Comment by xperiandri** [comment]
What about streams and ADO.NET classes that use `Close`? Where `Dispose` calls `Close` and may be exposed via interface only

**Comment by xperiandri** [comment]
``` C#
SqlConnection connection = null;
SqlCommand command = null;
SqlDataReader reader = null;
try
{
    connection = new SqlConnection(connectionString);
    await connection.OpenAsync();

    command = connection.CreateCommand();
    command.Connection = connection;
    command.CommandText = "";
    command.CommandType = CommandType.Text;
    stopWatch.Start();
    reader = await command.ExecuteReaderAsync(); // << warning!!!
    stopWatch.Stop();
    LoggerHelper.LogStress("LoadCustomerInformations", "SELECT [Name]", stopWatch.Elapsed, "");
    stopWatch.Restart();
    while (await reader.ReadAsync())
    {
        customerInformations.Add(new KeyValuePair<string, string>((string)reader["Name"], (string)reader["ConnectionString"]));
    }
    LoggerHelper.LogStress("LoadCustomerInformations", null, stopWatch.Elapsed, "");
}
finally
{
    reader?.Close();
    connection?.Dispose();
    command?.Dispose();
}

```

**Comment by BADF00D** [comment]
Hi,
I just disassembled the SqlDataReader and can now confirm, that Close of base class DbDataReader calls Close in Dispose:

```csharp
/// <summary>Releases the managed resources used by the <see cref="T:System.Data.Common.DbDataReader" /> and optionally releases the unmanaged resources.</summary>
    /// <param name="disposing">
    /// <see langword="true" /> to release managed and unmanaged resources; <see langword="false" /> to release only unmanaged resources.</param>
    protected virtual void Dispose(bool disposing)
    {
      if (!disposing)
        return;
      this.Close();
    }
```
So a call to Close on all DbDataReader can be seen as a call to Dispose.
* System.Data.DataTableReader
* System.Data.OdbcDataReader
* System.Data.OleDbDataReader
* System.Data.OracleDataReader
* System.Data.SqlDataReader
* System.Data.SqlDataReaderSmi

I created a new ticket #70 for this additional classes.

**Comment by xperiandri** [comment]
Thanks
