### ISSUE TITLE
this.Property.Dispose() is not recognized

### ISSUE THREAD

**Issue by Khaos66** [BADF00D/DisposableFixer#89]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am running the latest version of DisposableFixer: 1.1.0
- [ x] I have searched [open](https://github.com/BADF00D/DisposableFixer/issues) and [closed](https://github.com/BADF00D/DisposableFixer/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a IDisposable-property is disposed with this.Property?.Dispose() this is not recognized and the DF0022 warning is generated for that property.
The "this." prefix is mandatory by our convention.
With VS 15.8.0: formating code (CTRL+E,CTRL+D) adds the "this." prefix automatically.

### Source Code
```csharp
   public class Dummy : IDisposable
    {
        public ManualResetEvent MRE { get; }
            = new ManualResetEvent(false);

        public void Dispose()
        {
            this.MRE?.Dispose();
        }
    }
```

**Comment by BADF00D** [comment]
I could verify the problem, thanks for reporting!

**Comment by BADF00D** [comment]
Will be part of release 1.1.1.
